### ISSUE TITLE
build testのワークフロー追加

### ISSUE THREAD

**Issue by tkuramot** [soma0822/webserv#19]
## 1. 概要
github actionsでbuildのテストするワークフローを追加する
https://github.com/soma0822/webserv/pull/5#discussion_r1500199713
`-Wall -Werror -Wextra`つけてコンパイルできるか確認する

**Comment by soma0822** [comment]
#27 
で同じようなの作っちゃったわ。
任せていいですか？

**Comment by soma0822** [comment]
一瞬でできそうだったからやっちゃいます
