### ISSUE TITLE
CGI: status 200 'OK'省略の可能性

### ISSUE THREAD

**Issue by soma0822** [soma0822/webserv#210]
## 1. 概要
CGI の出力がstatus 200 'OK'を省略している場合に追加する。
Content-typeがあるかも確認して、なければ勝手に足すのかな？
エラーでもいい？
## 3. 提案内容
RFC
The script MUST return a Content-Type header field. A Status header field is optional, and status 200 'OK' is assumed if it is omitted. The server MUST make any appropriate modifications to the script's output to ensure that the response to the client complies with the response protocol version.
## 4. タスク
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by soma0822** [comment]
@kaaaaakun CGIの出力で一行目にHTTP/1.1 200 OK みたいな行がある時があるから、それもパースできるようにしてくれると助かります。（ない時もある）

**Comment by kaaaaakun** [comment]
すまぬ見落としてた。
一行目にHTTP/1.1 200 OK があると、今のだとエラーになっちゃうから、パーサ変えておいた方がいいよね？
