### ISSUE TITLE
RequestHandlerがCGIを実行した場合

### ISSUE THREAD

**Issue by soma0822** [soma0822/webserv#230]
## 1. 概要
RequestHandlerがCGIを実行した場合、responseを返さないので、その部分の対応。
## 3. 提案内容
Result型を使う
Err(kCGIexec);　エラーじゃないのにErrでやるのもうーん
Ok(NULL);　　　NULLで返すのも意味わかんない
のどっちにするか検討？
## 4. タスク
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by tkuramot** [comment]
Option型みたいなの作る？
https://qiita.com/take4s5i/items/c890fa66db3f71f41ce7

**Comment by soma0822** [comment]
あー、あり。
std::pair<HTTPResponse *, bool cgi_exec>　だと汚い？

**Comment by soma0822** [comment]
@tkuramot

**Comment by tkuramot** [comment]
- Option型
  - 値が入っているか入ってないかのどちらかに強制できる
  - 作るのが手間

- pair型
  - 値と同時にtrueも入れることが可能ではあるから、間違えやすくなったりレビューで気にすることが増えるかも
  - 追加で作るものがない

みたいな感じかな。
他で同じようなことをするならOption型作っても良さそうだけど、多分なさそうだしpair型めっちゃありな気はする

**Comment by soma0822** [comment]
std::pairでやっても
`HTTPResponse *HTTPResponse::Builder::Build() {
  response_->SetHTTPVersion(kHTTPVersion);
  if (response_->GetStatusCode() == http::kNone) {
    delete response_;
    return NULL;
  }
  return response_;
}`
このNULLとの見分けがめんどくさい。
Result型使って、この時のNULLを明確にErrで返して、CGIを実行した場合Ok(NULL)で返した方がわかりやすいかも
@tkuramot

**Comment by tkuramot** [comment]
Buildで失敗したNULLなのかそれとも値がない（CGI）かを判別するためにpairのboolだったりOption型が使えるってことではない？
```cpp
// pairの場合も同じ感じに
Option<HTTPResponse *> handler() {
  if (cgi_get) {
    return None<HTTPResponse *>(); // HTTPResponseを返さない
  }
  if (normal_get) {
    return Some<HTTPResponse *>(BuiltResponse);
  }
}

int main() {
  Option<HTTPResponse *> opt = handler();
  if (opt.IsSome()) {
    // normal request
    // buildで失敗してNULLの可能性がある
  } else {
    // cgi request
    // そもそも戻り値としてHTTPResponseがない
  }
}
```
BuildのNULLと何を見分けるときが面倒になってきます？あんまりイメージできてないです

現状確かにBuildの戻り値がポインタで成功したかどうかが明らかでない問題はあるし、全体としてResultにするのも良さそう。
その場合、関連してHTTPResponse::Builder::Buildでエラーの時にはInternalServerErrorを返すようにしてもいいかな。

**Comment by soma0822** [comment]
optionならわかりやすいか。
pairだとそのboolに名前がつかないから、なんのboolか分かりにくいなって思った

**Comment by tkuramot** [comment]
> pairだとそのboolに名前がつかないから、なんのboolか分かりにくいなって思った

確かにそれはありそう。Optionは以前作ったやつがあったのでpr出します

**Comment by soma0822** [comment]
ありがとうございます！
