### ISSUE TITLE
ステータスラインの形式の話

### ISSUE THREAD

**Issue by kaaaaakun** [soma0822/webserv#262]

**Comment by kaaaaakun** [comment]
A server MUST send the space that separates the status-code from the reason-phrase even when the reason-phrase is absent (i.e., the status-line would end with the space).(ステータスラインの中で、status:200 okとかの時に200の後の空白は必ず必要。ok(reason-phrase)がない場合でも必ず空白が必要 #262

**Comment by kaaaaakun** [comment]
@tkuramot @soma0822 
レスポンス返す時って、必ず`status:数字 空白 [理由]`の形式になってるよね？
(理由の部分がなくても)数字の後ろの空白がMUSTだったので、一応確認しました。
現状、reason-phraseがあるから必ず空白も入ってるから大丈夫だよね？

問題なかったら、closeしちゃってください〜

**Comment by soma0822** [comment]
@kaaaaakun @tkuramot 
`
std::string HTTPResponse::ToString() {
  std::ostringstream ss;

  // ステータスライン
  ss << http_version_ << " " << status_code_ << " "
     << GetStatusMessage(status_code_) << "\r\n";
`
倉本さん優秀なのでなってます

**Comment by kaaaaakun** [comment]
天才だった！！あざます！！！！！
