### ISSUE TITLE
const_iterator !

### ISSUE THREAD

**Issue by tkuramot** [soma0822/webserv#79]
## 1. 概要
const_iteratorはよくないかも！

getterはconst参照で返してたけど、Resultで参照返すのがよさそう？

## 4. タスク
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by soma0822** [comment]
ServerContextの出力で使ってる、const_iteratorは残してもいい？
デバッグ用だから、提出時は無くして、operator<<自体をprivateに入れる説
