### ISSUE TITLE
configのlocationプレフィックスにどこまで対応しますか？

### ISSUE THREAD

**Issue by soma0822** [soma0822/webserv#90]
## 1. 概要
configのlocationプレフィックスにどこまで対応しますか？
## 4. タスク

![スクリーンショット 2024-03-03 14 06 24](https://github.com/soma0822/webserv/assets/120237021/9e210e0c-ccf5-4b99-b3ea-2d63d74a0bc8)

https://heartbeats.jp/hbblog/2012/04/nginx05.html

**Comment by tkuramot** [comment]
cppのregexがC++11で使えないから、正規表現は扱わない方がよさそう
regexの実装は重すぎる気がする
`なし`と`=`？

**Comment by soma0822** [comment]
• Setup routes with one or multiple of the following rules/configuration (routes wont
be using regexp):
サブジェクトに明記あった。=は対応する感じにするか
